modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]] #mandatory
modId="supercharge"
version="${file.jarVersion}"
displayName="Supercharge"
displayURL="http://lugocorp.net/"
logoFile="examplemod.png"
credits="Brought to you by LugoCorp"
authors="Alex Lugo"
description='''
This is a mod that supercharges enemy spawns and resource farming. More enemies spawn at night and they have much better drop rates.

Secure renewable resource points and build up a base to defend yourself from night raids.
'''

[[dependencies.supercharge]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.supercharge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
